name: facebook
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # UI and Design
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  gap: ^3.0.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.8.0+1

  # Image & Asset Handling
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Code Quality
  flutter_lints:
    ^5.0.0

    # Code Generation
  flutter_gen_runner: ^5.9.0
  flutter_gen: ^5.9.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  # Asset directories
  assets:
    - assets/images/
    - assets/svgs/

  # Fonts
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700
